version: "2"

run:
  tests: true
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unused
  settings:
    lll:
      line-length: 88
      tab-width: 4
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  new-from-rev: HEAD~1

formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - builtin$
      - third_party$
      - examples$
