name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to fill out this bug report! Please be as
        descriptive about the bug as you possibly can. It will help us better
        understand at identifying the root cause of the bug.

  - type: textarea
    id: what-happened
    attributes:
      label: Explain where the bug is
      description:
        Elaborate the unintended behaviour and why you believe it is a bug and
        what the intended behaviour should be like.
      placeholder: Explain the bug and the intended behaviour in detail.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description:
        Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: Shell

  - type: textarea
    id: screenshots
    attributes:
      label: Share relevant screenshots, if possible
      description:
        Please share a screenshot or two, if possible. This will help us better
        understand the bug and fix it!
