name: Code Linting

on:
  pull_request:
    branches:
      - main
    paths:
      - "*.go"
  push:
    branches:
      - main
    paths:
      - "*.go"

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.64

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          only-new-issues: true
